// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbtdjspNB_HmMveraTTykOgqLYgo0fjKY',
    appId: '1:503611800139:web:29d51bf0da77d1a3626bce',
    messagingSenderId: '503611800139',
    projectId: 'habitapp-98af1',
    authDomain: 'habitapp-98af1.firebaseapp.com',
    storageBucket: 'habitapp-98af1.firebasestorage.app',
    measurementId: 'G-J9VCHV74V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJmKjtVP5QcqoMIYQsl_-lFD2w8cnMffM',
    appId: '1:503611800139:android:64f32869e66c8f9c626bce',
    messagingSenderId: '503611800139',
    projectId: 'habitapp-98af1',
    storageBucket: 'habitapp-98af1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT0Ictw8GuS3hXehtbCvNmikiahFxP8D8',
    appId: '1:503611800139:ios:b8d4373f1f4df4af626bce',
    messagingSenderId: '503611800139',
    projectId: 'habitapp-98af1',
    storageBucket: 'habitapp-98af1.firebasestorage.app',
    iosBundleId: 'com.example.habitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT0Ictw8GuS3hXehtbCvNmikiahFxP8D8',
    appId: '1:503611800139:ios:b8d4373f1f4df4af626bce',
    messagingSenderId: '503611800139',
    projectId: 'habitapp-98af1',
    storageBucket: 'habitapp-98af1.firebasestorage.app',
    iosBundleId: 'com.example.habitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbtdjspNB_HmMveraTTykOgqLYgo0fjKY',
    appId: '1:503611800139:web:f6f9f8dae288d206626bce',
    messagingSenderId: '503611800139',
    projectId: 'habitapp-98af1',
    authDomain: 'habitapp-98af1.firebaseapp.com',
    storageBucket: 'habitapp-98af1.firebasestorage.app',
    measurementId: 'G-13RC1PHNVY',
  );
}
